### ISSUE TITLE
CWR hides all the test output

### ISSUE THREAD

**Issue by ktsakalozos** [juju-solutions/layer-cwr#38]
The tests output does not go through stdout so upon completion you get a red build without knowing why. Ideally the xml test format of cwr should be put into use and the results imported to Jenkins

**Comment by bbcmicrocomputer** [comment]
Definitely want to see something done here.

It's impossible to tell what a charm/bundle Jenkins job is doing as it runs or what issues there are. These logs should be as verbose as possible.

**Comment by seman** [comment]
Are you running cwr with `-l DEBUG -v` options?
