### ISSUE TITLE
handle "check_bundle" returning False

### ISSUE THREAD

**Issue by kwmonroe** [juju-solutions/layer-cwr#51]
As written, it seems `check_bundle` will return False if `should_trigger_build` returns False:

https://github.com/juju-solutions/layer-cwr/blob/master/scripts/bundlebuilder.py#L388

When this happens, the job will fail because anytime `check_bundle` returns False, we `sys.exit(1)`:

https://github.com/juju-solutions/layer-cwr/blob/master/scripts/bundlebuilder.py#L450

I think we either need to alter the return of `check-bundle` or better handle the case(s) for when a bundle build does not need to run.

**Comment by ktsakalozos** [comment]
Thank you for putting bundle-building onto test!

The idea behind check-bundle is that it be triggered periodically and succeed only if a build-bundle (should_trigger_build) is required. A green check-build triggers the build-bundle jenkins job that will do the job of update and release the bundle.

I do not see a way to check if a bundle update is required other than running a jenkins job.
