### ISSUE TITLE
Surface errors if Jenkins plugin install fails

### ISSUE THREAD

**Issue by johnsca** [juju-solutions/layer-cwr#63]
If plugins fail to install, such as due to network connectivity, the charm doesn't notice and continues on without the plugins.  This causes misleading errors when jobs are attempted.

**Comment by johnsca** [comment]
It would also be good to have a sanity check for `-f metadata.yaml` in the job just to verify that the repo clone worked as expected.

**Comment by ktsakalozos** [comment]
Creating  a separate issue for the check up on metadata.yaml.
