### ISSUE TITLE
Juju logs should be imported to jenkins job

### ISSUE THREAD

**Issue by bbcmicrocomputer** [juju-solutions/layer-cwr#76]
Whether a Jenkins job succeeds or fails, Juju logs (/var/log/juju/*) from the deployment should be imported.

When something fails the deployment is typically destroyed instantly making it extremely difficult to investigate why.

A CI system should always be as verbose as possible in logging and collecting artifacts which instruct the user why a build failed.

**Comment by johnsca** [comment]
This is handled by juju-crashdump on failure.

**Comment by kwmonroe** [comment]
And to follow up, the crashdump bits are linked into the jenkins jobs dirs.
