### ISSUE TITLE
'data stored in an older format ...' jenkins alert

### ISSUE THREAD

**Issue by bbcmicrocomputer** [juju-solutions/layer-cwr#77]
After running one of the cwr workflow actions, when I log into Jenkins I see an alert:

'You have data stored in an older format and/or unreadable data'

Have attached screenshot.

![screenshot from 2017-02-09 13-52-42](https://cloud.githubusercontent.com/assets/6774503/22937811/a3cf0d78-f2d1-11e6-9b7b-0cc7e6d6e055.png)

**Comment by ktsakalozos** [comment]
I have seen this error when a plugin gets partially installed. Can you check under Manage Plugins to see if everything is in order?

**Comment by bbcmicrocomputer** [comment]
Manage Plugins looks fine.

You're probably right, it's just an error related to a bodged install.
