### ISSUE TITLE
Juju hook error should be retried similarly to juju 2.0

### ISSUE THREAD

**Issue by bbcmicrocomputer** [juju-solutions/layer-cwr#78]
When running deployment tests, if a hook fails, the environment is immediately destroyed and a job build is marked as a failure.

This behaviour helped me diagnose a previously unknown timing bug within a charm (which is great!). 
Typically if this bug surfaces Juju 2.0 will retry failed hooks at least 3 times which enables deployment to continue.

I think it'd be a great enhancement if cwr could retry hooks at least 3 times similarly. It should still note+flag each hook failure for the user to inspect, but it should try and continue past hook failure. It provides more depth to testing and allows people to work more efficiently with test results.

**Comment by johnsca** [comment]
This was fixed with the update to bundletester to use native deploy.
